"$schema" = "./node_modules/wrangler/config-schema.json"
name = "jobpls"
compatibility_date = "2026-02-09"
compatibility_flags = [ "nodejs_compat" ]
main = "workers/index.ts"

[assets]
not_found_handling = "single-page-application"
run_worker_first = [ "/api/*" ]

[observability]
[observability.logs]
enabled = true
invocation_logs = true


[vars]
FEATURE_PAYMENTS = "false"
FEATURE_DEV_SEED = "true"
BETTER_AUTH_URL = "http://localhost:3000"

[[d1_databases]]
binding = "DB"
database_name = "jobpls-db"
database_id = "27dc0f08-d055-4d0a-b1a8-cabd1dc6a9bb"
migrations_dir = "./src/db/migrations"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "jobpls_events"

[env.development]
name="jobpls"

  [env.development.vars]
  FEATURE_PAYMENTS = "false"
  FEATURE_DEV_SEED = "true"
  BETTER_AUTH_URL = "http://localhost:3000"

  [[env.development.d1_databases]]
  binding = "DB"
  database_name = "jobpls-db"
  database_id = "27dc0f08-d055-4d0a-b1a8-cabd1dc6a9bb"
  migrations_dir = "./src/db/migrations"

[env.production]
name="jobpls"
routes = ["jobpls.lol/*"]

  [env.production.vars]
  FEATURE_PAYMENTS = "false"
  FEATURE_DEV_SEED = "false"
  BETTER_AUTH_URL = "https://jobpls.lol"

  [env.production.observability]
  enabled = true
  head_sampling_rate = 1

  [[env.production.d1_databases]]
  binding = "DB"
  database_name = "jobpls-db"
  database_id = "27dc0f08-d055-4d0a-b1a8-cabd1dc6a9bb"
  migrations_dir = "./src/db/migrations"

  [[env.production.analytics_engine_datasets]]
  binding = "ANALYTICS"
  dataset = "jobpls_events"
