/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as CvTemplateRouteImport } from './routes/cv-template'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutMeRouteImport } from './routes/about-me'
import { Route as IndexRouteImport } from './routes/index'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const CvTemplateRoute = CvTemplateRouteImport.update({
  id: '/cv-template',
  path: '/cv-template',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/account': typeof AccountRoute
  '/cv-template': typeof CvTemplateRoute
  '/generate': typeof GenerateRoute
  '/home': typeof HomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/account': typeof AccountRoute
  '/cv-template': typeof CvTemplateRoute
  '/generate': typeof GenerateRoute
  '/home': typeof HomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/account': typeof AccountRoute
  '/cv-template': typeof CvTemplateRoute
  '/generate': typeof GenerateRoute
  '/home': typeof HomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-me'
    | '/account'
    | '/cv-template'
    | '/generate'
    | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about-me' | '/account' | '/cv-template' | '/generate' | '/home'
  id:
    | '__root__'
    | '/'
    | '/about-me'
    | '/account'
    | '/cv-template'
    | '/generate'
    | '/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutMeRoute: typeof AboutMeRoute
  AccountRoute: typeof AccountRoute
  CvTemplateRoute: typeof CvTemplateRoute
  GenerateRoute: typeof GenerateRoute
  HomeRoute: typeof HomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv-template': {
      id: '/cv-template'
      path: '/cv-template'
      fullPath: '/cv-template'
      preLoaderRoute: typeof CvTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutMeRoute: AboutMeRoute,
  AccountRoute: AccountRoute,
  CvTemplateRoute: CvTemplateRoute,
  GenerateRoute: GenerateRoute,
  HomeRoute: HomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
